apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tdemo-python1
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tdemo-python1
spec:
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: test
  build:
    env:
      - name: BP_FUNCTION
        value: func.test
